server:
  port: 9090

spring:
  application:
    name: admin
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/admin
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/changelog.xml

analytics:
  url: http://localhost:9091

jwt:
  token:
    secret: adminapp
    expired: ${TOKEN_EXPIRED:3600000}

#logging:
#  level:
#    root: DEBUG