
server:
  port: 9090

spring:
  application:
    name: admin
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/botadmin
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none


analytics:
  url: http://localhost:9091